[workspace]
authors = ["Derek Veit <derek.veit>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "lidar_reader"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = ">=0.26.2.0.dev2026020105,<0.27"

[pypi-dependencies]
pygame = ">=2.6.1, <3"
